---
title: "Pathogen"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
a<-read.csv('~/pth.csv')
library(dplyr)

b<-t(a)
colnames(b)=b[1,]
d=b[-1,]

dt<-as.data.frame(d)

dt[,1]

dt[,1]<- as.numeric(dt[,1])

od<-dt[order(dt[,1]),]


od[,3:11]<-as.numeric(unlist(od[,3:11]))

rownames(od)=od[,2]

gg=od[,-1]

gg$sa=factor(gg$sa, levels = c(gg$sa)) #Set levels So that the x-axis in plot is in correct order.

rawdata<-gg

library(reshape2)
mt <- melt(data=rawdata,id.vars=c("sa"),variable.name="Pathogen",value.name="level")
level<- 1*(mt$level)
#daozhe

Sample = mt$sa
RA = level*100
Pathogen = mt$Pathogen
```

```{r}
library(ggplot2)
library(ggbreak)
pth <- ggplot(mt, aes(x=Sample, y=RA, fill= Pathogen)) + 
  #geom_bar(stat="identity", width=1, position = position_dodge(3)) +
  geom_col(position = 'stack', width = 0.6) +
  xlab("Sample") + ylab("Relative Abundance (%)") +   
  theme_classic() +
  #theme_gray() +
  #theme_minimal() +
  #theme_bw() +
  #coord_cartesian(ylim = c(0, 0.7))
#scale_y_discrete(break = c(0,0.014))
#theme(axis.ticks.x.top = element_line(),  axis.line = element_blank())
  scale_y_break(c(4, 6), 
                  scale = 0.5,
                  space = 0.1,
                  ticklabels = c(6,9,12,15,18,21,24),
                  expand = expansion(mult = c(0, 0.05)))

library(RColorBrewer)
palette0 <- brewer.pal(12,"Paired")
#palette3 <- brewer.pal(1,"Set3")
#big_palette <- c(palette0, palette3)

pth + theme(axis.text.x = element_text(angle = 45,
                                       hjust = 1,
                                       size = 10)) +
  theme(axis.text.y = element_text(lineheight = 1, 
                                   size = 10)) +
  scale_fill_manual(values = palette0) 
  #scale_y_continuous(expand = c(0,0))
```

```{r}
ggsave("~/Desktop/pth_new.png",width=10,height=7,dpi="retina")
```

